WITH RAW AS (
    SELECT *
    FROM {{ source('RAW', 'MENU') }}
),

CLEANED AS (
    SELECT 
        MENU_ID,
        MENU_TYPE_ID,
        INITCAP(MENU_TYPE) AS MENU_TYPE,
        INITCAP(TRUCK_BRAND_NAME) AS TRUCK_BRAND_NAME,
        MENU_ITEM_ID,
        INITCAP(MENU_ITEM_NAME) AS MENU_ITEM_NAME,
        INITCAP(ITEM_CATEGORY) AS ITEM_CATEGORY,
        INITCAP(ITEM_SUBCATEGORY) AS ITEM_SUBCATEGORY,
        COST_OF_GOODS_USD,
        SALE_PRICE_USD,
        INGREDIENTS
    FROM RAW
    QUALIFY ROW_NUMBER() OVER (PARTITION BY MENU_ID,MENU_TYPE_ID,MENU_ITEM_ID ORDER BY MENU_ID,MENU_TYPE_ID,MENU_ITEM_ID) = 1
)

SELECT *
FROM CLEANED
