WITH RAW AS (
    SELECT *
    FROM {{ source('RAW', 'LOCATION') }}
),

CLEANED AS (
    SELECT 
        LOCATION_ID,
        TRIM(LOCATION_PLACEKEY) AS LOCATION_PLACEKEY,
        LOCATION_NAME,
        INITCAP(CITY) AS CITY_NAME,
        INITCAP(REGION) AS REGION,
        UPPER(ISO_COUNTRY_CODE) AS ISO_COUNTRY_CODE,
        INITCAP(COUNTRY) AS COUNTRY_NAME
    FROM RAW
)

SELECT *
FROM CLEANED