WITH RAW AS (
    SELECT *
    FROM {{ source('RAW', 'CUSTOMER_LOYALTY') }}
),

CLEANED AS (
    SELECT 
        CUSTOMER_ID,
        INITCAP(FIRST_NAME) AS FIRST_NAME,
        INITCAP(LAST_NAME) AS LAST_NAME,
        INITCAP(CITY) AS CITY_NAME,
        INITCAP(COUNTRY) AS COUNTRY_NAME,
        TRIM(POSTAL_CODE) AS POSTAL_CODE,
        INITCAP(PREFERRED_LANGUAGE) AS PREFERRED_LANGUAGE,
        INITCAP(TRIM(GENDER)) AS GENDER,
        INITCAP(FAVOURITE_BRAND) AS FAVOURITE_BRAND,
        INITCAP(MARITAL_STATUS) AS MARITAL_STATUS,
        CHILDREN_COUNT,
        SIGN_UP_DATE,
        BIRTHDAY_DATE,
        TRIM(EMAIL) AS EMAIL,
        PHONE_NUMBER
    FROM RAW
    WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM {{ ref('stg_order_header') }})
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID,FIRST_NAME,LAST_NAME,CITY_NAME ORDER BY CUSTOMER_ID,FIRST_NAME,LAST_NAME,CITY_NAME) = 1
    LIMIT 10000
)

SELECT *
FROM CLEANED
