WITH RAW AS ( 
    SELECT * 
    FROM {{ source('RAW', 'FRANCHISE') }} 
), 

CLEANED AS ( 
    SELECT 
        FRANCHISE_ID, 
        INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME, 
        INITCAP(TRIM(LAST_NAME)) AS LAST_NAME, 
        INITCAP(CITY) AS CITY_NAME, 
        INITCAP(COUNTRY) AS COUNTRY_NAME, 
        TRIM(EMAIL) AS EMAIL , 
        PHONE_NUMBER 
    FROM RAW 
)     

SELECT * 
FROM CLEANED