WITH RAW AS (
    SELECT *
    FROM {{ source('RAW', 'TRUCK') }}
),

CLEANED AS (
    SELECT 
        TRUCK_ID,
        MENU_TYPE_ID,
        INITCAP(PRIMARY_CITY) AS CITY_NAME,
        INITCAP(REGION) AS REGION,
        UPPER(ISO_REGION) AS ISO_REGION,
        INITCAP(COUNTRY) AS COUNTRY_NAME,
        UPPER(ISO_COUNTRY_CODE) AS ISO_COUNTRY_CODE,
        FRANCHISE_FLAG,
        TRIM(YEAR) AS YEAR,
        INITCAP(MAKE) AS MAKE,
        MODEL,
        EV_FLAG,
        FRANCHISE_ID,
        TRUCK_OPENING_DATE
    FROM RAW
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRUCK_ID,MENU_TYPE_ID,CITY_NAME ORDER BY TRUCK_ID,MENU_TYPE_ID,CITY_NAME) = 1
)

SELECT *
FROM CLEANED
