WITH RAW AS ( 
    SELECT * 
    FROM {{ source('RAW' , 'COUNTRY') }} 
), 

CLEANED AS ( 
    SELECT 
        COUNTRY_ID, 
        INITCAP(COUNTRY_NAME) AS COUNTRY_NAME, 
        UPPER(TRIM(ISO_CURRENCY)) AS ISO_CURRENCY, 
        UPPER(TRIM(ISO_CODE)) AS ISO_CODE, 
        CITY_ID, 
        INITCAP(CITY_NAME) AS CITY_NAME, 
        CITY_POPULATION 
    FROM RAW 
) 

SELECT * 
FROM CLEANED