name: taco_bytes
version: 1.0.0
config-version: 2
profile: taco_bytes
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  taco_bytes:
    staging:
      +schema: staging
      +materialized: table
    core:
      +schema: core_df
      +materialized: table
    
