taco_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DEVELOPER_ROLE
      warehouse: XSMALL_WH
      database: TACO_BYTES_DBT_DB
      schema: RAW