-- TACO BYTES STEP 1 


CREATE OR REPLACE DATABASE TACO_BYTES_DBT_DB;
CREATE OR REPLACE SCHEMA TACO_BYTES_DBT_DB.RAW;

USE DATABASE TACO_BYTES_DBT_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES
COMMENT = 'LOAD DATA FROM S3'
URL = 's3://sfquickstarts/frostbyte_tastybytes/';

CREATE OR REPLACE FILE FORMAT TACO_BYTES_DBT_DB.RAW.FF_TACO_BYTES_CSV
    TYPE = 'csv';

LIST @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos;

-- TABLE 1 COUNTRY
-- WE NEED TO USE INFER_SCHEMA TO KNOW THE NO OF COLUMN PRESENTED IN THE FILE

SELECT *
FROM TABLE(
    INFER_SCHEMA(
    LOCATION => '@TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/country',
    FILE_FORMAT => 'FF_TACO_BYTES_CSV'
    )
);

SELECT 
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/country
(FILE_FORMAT => 'FF_TACO_BYTES_CSV');

CREATE OR REPLACE TABLE RAW.COUNTRY (
    COUNTRY_ID NUMBER(3,0),
    COUNTRY_NAME VARCHAR(100),
    ISO_CURRENCY VARCHAR(3),
    ISO_CODE VARCHAR(2),
    CITY_ID NUMBER(18,0),
    CITY_NAME VARCHAR(100),
    CITY_POPULATION NUMBER(18,0)
    CONSTRAINT PK_COUNTRY PRIMARY KEY (COUNTRY_ID, CITY_ID)
);
    
COPY INTO RAW.COUNTRY
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/country
FILE_FORMAT = 'FF_TACO_BYTES_CSV';

SELECT * FROM RAW.COUNTRY LIMIT 10;

-- TABLE 2 FRANCHISE

SELECT *
FROM TABLE(
    INFER_SCHEMA(
    LOCATION => '@TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/franchise',
    FILE_FORMAT => 'FF_TACO_BYTES_CSV'
    )
);

SELECT 
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/franchise
(FILE_FORMAT => 'FF_TACO_BYTES_CSV');

CREATE OR REPLACE TABLE RAW.FRANCHISE (
    FRANCHISE_ID NUMBER(18,0),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    CITY VARCHAR(100),
    COUNTRY VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    CONSTRAINT PK_FRANCHISE PRIMARY KEY (FRANCHISE_ID, EMAIL, PHONE_NUMBER)
);

COPY INTO RAW.FRANCHISE 
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/franchise
FILE_FORMAT = 'FF_TACO_BYTES_CSV';

SELECT * FROM RAW.FRANCHISE LIMIT 10;

-- TABLE 3 LOCATION

SELECT *
FROM TABLE (
    INFER_SCHEMA(
    LOCATION => '@TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/location',
    FILE_FORMAT => 'FF_TACO_BYTES_CSV'
    )
);

SELECT 
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/location
(FILE_FORMAT => 'FF_TACO_BYTES_CSV');

CREATE OR REPLACE TABLE LOCATION (
    LOCATION_ID NUMBER(18,0),
    LOCATION_PLACEKEY VARCHAR(100),
    LOCATION_NAME VARCHAR(1000),
    CITY VARCHAR(100),
    REGION VARCHAR(100),
    ISO_COUNTRY_CODE VARCHAR(2),
    COUNTRY VARCHAR(100),
    CONSTRAINT PK_LOCATION PRIMARY KEY (LOCATION_ID,LOCATION_PLACEKEY, LOCATION_NAME)
);

COPY INTO RAW.LOCATION
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/location
FILE_FORMAT = 'FF_TACO_BYTES_CSV';

SELECT * FROM RAW.LOCATION LIMIT 10;

-- TABLE 4 MENU

SELECT *
FROM TABLE (
    INFER_SCHEMA(
    LOCATION => '@TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/menu',
    FILE_FORMAT => 'FF_TACO_BYTES_CSV'
    )
);

SELECT 
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/menu
(FILE_FORMAT => 'FF_TACO_BYTES_CSV');


CREATE OR REPLACE TABLE RAW.MENU
(
    MENU_ID NUMBER(18,0),
    MENU_TYPE_ID NUMBER(38,0),
    MENU_TYPE VARCHAR(16777216),
    TRUCK_BRAND_NAME VARCHAR(16777216),
    MENU_ITEM_ID NUMBER(38,0),
    MENU_ITEM_NAME VARCHAR(16777216),
    ITEM_CATEGORY VARCHAR(16777216),
    ITEM_SUBCATEGORY VARCHAR(16777216),
    COST_OF_GOODS_USD NUMBER(38,4),
    SALE_PRICE_USD NUMBER(38,4),
    INGREDIENTS VARIANT
);

COPY INTO RAW.MENU 
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/menu
FILE_FORMAT = 'FF_TACO_BYTES_CSV';  

SELECT * FROM RAW.MENU LIMIT 10;

-- TABLE 5 TRUCK

SELECT *
FROM TABLE (
    INFER_SCHEMA(
    LOCATION => '@TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/truck',
    FILE_FORMAT => 'FF_TACO_BYTES_CSV'
    )
);

SELECT 
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/truck
(FILE_FORMAT => 'FF_TACO_BYTES_CSV');

CREATE OR REPLACE TABLE RAW.TRUCK
(
    TRUCK_ID NUMBER(38,0),
    MENU_TYPE_ID NUMBER(38,0),
    PRIMARY_CITY VARCHAR(16777216),
    REGION VARCHAR(16777216),
    ISO_REGION VARCHAR(16777216),
    COUNTRY VARCHAR(16777216),
    ISO_COUNTRY_CODE VARCHAR(16777216),
    FRANCHISE_FLAG NUMBER(38,0),
    YEAR NUMBER(38,0),
    MAKE VARCHAR(16777216),
    MODEL VARCHAR(16777216),
    EV_FLAG NUMBER(38,0),
    FRANCHISE_ID NUMBER(38,0),
    TRUCK_OPENING_DATE DATE
);

COPY INTO RAW.TRUCK
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/truck
FILE_FORMAT = 'FF_TACO_BYTES_CSV';

SELECT * FROM TRUCK LIMIT 10;

-- TABLE 6 ORDER_HEADER 

SELECT *
FROM TABLE (
    INFER_SCHEMA(
    LOCATION => '@TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/order_header',
    FILE_FORMAT => 'FF_TACO_BYTES_CSV'
    )
);

SELECT 
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/order_header
(FILE_FORMAT => 'FF_TACO_BYTES_CSV');

CREATE OR REPLACE TABLE RAW.ORDER_HEADER
(
    ORDER_ID NUMBER(38,0),
    TRUCK_ID NUMBER(38,0),
    LOCATION_ID NUMBER(38,0),
    CUSTOMER_ID NUMBER(38,0),
    DISCOUNT_ID VARCHAR(16777216),
    SHIFT_ID NUMBER(38,0),
    SHIFT_START_TIME TIME(9),
    SHIFT_END_TIME TIME(9),
    ORDER_CHANNEL VARCHAR(16777216),
    ORDER_TS TIMESTAMP_NTZ(9),
    SERVED_TS VARCHAR(16777216),
    ORDER_CURRENCY VARCHAR(3),
    ORDER_AMOUNT NUMBER(38,4),
    ORDER_TAX_AMOUNT VARCHAR(16777216),
    ORDER_DISCOUNT_AMOUNT VARCHAR(16777216),
    ORDER_TOTAL NUMBER(38,4)
);

COPY INTO RAW.ORDER_HEADER
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/order_header
FILE_FORMAT = 'FF_TACO_BYTES_CSV';

SELECT * FROM ORDER_HEADER LIMIT 10;

-- TABLE 7 ORDER_DETAILS

SELECT *
FROM TABLE (
    INFER_SCHEMA(
    LOCATION => '@TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/order_detail',
    FILE_FORMAT => 'FF_TACO_BYTES_CSV'
    )
);

SELECT 
    $1, $2, $3, $4, $5, $6, $7, $8, $9
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/order_detail
(FILE_FORMAT => 'FF_TACO_BYTES_CSV');

CREATE OR REPLACE TABLE RAW.ORDER_DETAIL 
(
    ORDER_DETAIL_ID NUMBER(38,0),
    ORDER_ID NUMBER(38,0),
    MENU_ITEM_ID NUMBER(38,0),
    DISCOUNT_ID VARCHAR(16777216),
    LINE_NUMBER NUMBER(38,0),
    QUANTITY NUMBER(5,0),
    UNIT_PRICE NUMBER(38,4),
    PRICE NUMBER(38,4),
    ORDER_ITEM_DISCOUNT_AMOUNT VARCHAR(16777216)
);

COPY INTO RAW.ORDER_DETAIL
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_pos/order_detail
FILE_FORMAT = 'FF_TACO_BYTES_CSV';

SELECT * FROM ORDER_DETAIL LIMIT 10;

-- TABLE 8 CUSTOMER_LOYALTY

SELECT *
FROM TABLE (
    INFER_SCHEMA(
    LOCATION => '@TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_customer/customer_loyalty',
    FILE_FORMAT => 'FF_TACO_BYTES_CSV'
    )
);

SELECT 
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_customer/customer_loyalty
(FILE_FORMAT => 'FF_TACO_BYTES_CSV');

CREATE OR REPLACE TABLE RAW.CUSTOMER_LOYALTY
(
    CUSTOMER_ID NUMBER(38,0),
    FIRST_NAME VARCHAR(16777216),
    LAST_NAME VARCHAR(16777216),
    CITY VARCHAR(16777216),
    COUNTRY VARCHAR(16777216),
    POSTAL_CODE VARCHAR(16777216),
    PREFERRED_LANGUAGE VARCHAR(16777216),
    GENDER VARCHAR(16777216),
    FAVOURITE_BRAND VARCHAR(16777216),
    MARITAL_STATUS VARCHAR(16777216),
    CHILDREN_COUNT VARCHAR(16777216),
    SIGN_UP_DATE DATE,
    BIRTHDAY_DATE DATE,
    EMAIL VARCHAR(16777216),
    PHONE_NUMBER VARCHAR(16777216)
);

COPY INTO RAW.CUSTOMER_LOYALTY
FROM @TACO_BYTES_DBT_DB.RAW.STG_TACO_BYTES/raw_customer/customer_loyalty
FILE_FORMAT = 'FF_TACO_BYTES_CSV';

SELECT * FROM CUSTOMER_LOYALTY LIMIT 10;

