WITH BASE AS (
    SELECT DISTINCT
        SHIFT_ID,
        SHIFT_START_TIME,
        SHIFT_END_TIME
    FROM {{ ref('stg_order_header') }}
)

SELECT 
    SHIFT_ID,
    TO_VARCHAR(SHIFT_START_TIME, 'HH12:MI AM') AS SHIFT_START_TIME,
    TO_VARCHAR(SHIFT_END_TIME, 'HH12:MI AM') AS SHIFT_END_TIME,
    CASE
        WHEN HOUR(SHIFT_START_TIME) BETWEEN 5 AND 11 THEN 'Morning'
        WHEN HOUR(SHIFT_START_TIME) BETWEEN 12 AND 17 THEN 'Afternoon'
        WHEN HOUR(SHIFT_START_TIME) BETWEEN 18 AND 22 THEN 'Evening'
        ELSE 'Night'
    END AS SHIFT_PART_OF_DAY
FROM BASE
