WITH DATES AS (
    SELECT 
        DATEADD(DAY, SEQ4(), '2019-01-01') AS DATE_DAY
    FROM TABLE(GENERATOR(ROWCOUNT => 365*5+1)) -- +1 Because there is 1 leap year 
)
SELECT
    DATE_DAY,
    YEAR(DATE_DAY) AS YEAR,
    MONTH(DATE_DAY) AS MONTH,
    MONTHNAME(DATE_DAY) AS MONTH_NAME,
    DAY(DATE_DAY) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_DAY) AS DAY_OF_WEEK,
    CASE 
        WHEN DAYOFWEEK(DATE_DAY) IN (0,6) THEN 'YES'
        ELSE 'NO'
    END AS IS_WEEKEND,
    QUARTER(DATE_DAY) AS QUARTER
FROM DATES
